## Lancia La lettura delle fatture da Namirial
POST http://localhost:4004/odata/v4/processor/getInvoices
Content-Type: application/json
### Lancia La lettura dei Clienti Ariba
POST http://localhost:4004/odata/v4/processor/getCustomers
Content-Type: application/json
### Lancia Invio delle fatture verso Ariba
POST http://localhost:4004/odata/v4/processor/sendInvoices
Content-Type: application/json
### Lancia Il Retry Delle Fatture verso Ariba
POST http://localhost:4004/odata/v4/processor/retryInvoices
Content-Type: application/json
